ALTER TABLE "Campaign"
ADD COLUMN "predictiveEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "adaptiveDialEnabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "autoDialLevel" DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN "minimumHopper" INTEGER NOT NULL DEFAULT 25,
ADD COLUMN "maximumHopper" INTEGER NOT NULL DEFAULT 200,
ADD COLUMN "hopperRefillInterval" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN "wrapUpTime" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN "maximumAbandonRate" DOUBLE PRECISION NOT NULL DEFAULT 0.03,
ADD COLUMN "maximumSimultaneousCalls" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN "maximumCallsPerAgent" DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN "callTimeout" INTEGER NOT NULL DEFAULT 60,
ADD COLUMN "ringTimeout" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN "agentReservationTime" INTEGER NOT NULL DEFAULT 15,
ADD COLUMN "maximumQueueWait" INTEGER NOT NULL DEFAULT 45,
ADD COLUMN "dialStatusFilter" JSONB,
ADD COLUMN "leadPriority" JSONB,
ADD COLUMN "callPriority" TEXT NOT NULL DEFAULT 'NORMAL',
ADD COLUMN "localCallTime" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "emergencyStopped" BOOLEAN NOT NULL DEFAULT false;

UPDATE "Campaign"
SET
  "predictiveEnabled" = CASE WHEN UPPER(COALESCE("mode", '')) = 'PREDICTIVE' THEN true ELSE false END,
  "autoDialLevel" = GREATEST(0, LEAST(3, COALESCE("dialingRatio", 1)::DOUBLE PRECISION)),
  "maximumCallsPerAgent" = GREATEST(1, LEAST(3, COALESCE("dialingRatio", 1)::DOUBLE PRECISION));
