ALTER TYPE "ContactStatus" ADD VALUE IF NOT EXISTS 'CONTACTED';
ALTER TYPE "ContactStatus" ADD VALUE IF NOT EXISTS 'VOICEMAIL';
ALTER TYPE "ContactStatus" ADD VALUE IF NOT EXISTS 'WRONG_NUMBER';

ALTER TABLE "Call"
ADD COLUMN IF NOT EXISTS "direction" TEXT,
ADD COLUMN IF NOT EXISTS "remoteNumber" TEXT,
ADD COLUMN IF NOT EXISTS "source" TEXT;
