import Joi from 'joi'

export const createCampaignSchema = Joi.object({
  name:        Joi.string().min(2).max(100).required(),
  description: Joi.string().max(500).optional().allow(''),
  mode:        Joi.string().valid('MANUAL', 'PREVIEW', 'PROGRESSIVE', 'PREDICTIVE').default('PROGRESSIVE'),
  dialRatio:   Joi.number().min(0).max(3).default(1),
  dialingRatio: Joi.number().min(0).max(3).optional(),
  predictiveEnabled: Joi.boolean().optional(),
  adaptiveDialEnabled: Joi.boolean().optional(),
  autoDialLevel: Joi.number().valid(0, 0.5, 1, 1.2, 1.5, 2, 2.5, 3).optional(),
  minimumHopper: Joi.number().integer().min(1).max(1000).optional(),
  maximumHopper: Joi.number().integer().min(1).max(5000).optional(),
  hopperRefillInterval: Joi.number().integer().min(5).max(3600).optional(),
  wrapUpTime: Joi.number().integer().min(0).max(3600).optional(),
  maximumAbandonRate: Joi.number().min(0).max(0.2).optional(),
  maximumSimultaneousCalls: Joi.number().integer().min(1).max(500).optional(),
  maximumCallsPerAgent: Joi.number().min(0.5).max(5).optional(),
  callTimeout: Joi.number().integer().min(5).max(600).optional(),
  ringTimeout: Joi.number().integer().min(5).max(300).optional(),
  agentReservationTime: Joi.number().integer().min(1).max(300).optional(),
  maximumQueueWait: Joi.number().integer().min(1).max(600).optional(),
  callPriority: Joi.string().max(40).optional(),
  localCallTime: Joi.boolean().optional(),
  emergencyStopped: Joi.boolean().optional(),
  maxRetries:  Joi.number().min(0).max(10).default(3),
  retryDelay:  Joi.number().min(30).max(86400).default(300),
  script:      Joi.string().max(5000).optional().allow(''),
  startTime:   Joi.string().pattern(/^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$/).optional(),
  endTime:     Joi.string().pattern(/^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$/).optional(),
  timezone:    Joi.string().default('Asia/Karachi'),
})

export const updateCampaignSchema = Joi.object({
  name:        Joi.string().min(2).max(100).optional(),
  description: Joi.string().max(500).optional().allow(''),
  mode:        Joi.string().valid('MANUAL', 'PREVIEW', 'PROGRESSIVE', 'PREDICTIVE').optional(),
  dialRatio:   Joi.number().min(0).max(3).optional(),
  dialingRatio: Joi.number().min(0).max(3).optional(),
  predictiveEnabled: Joi.boolean().optional(),
  adaptiveDialEnabled: Joi.boolean().optional(),
  autoDialLevel: Joi.number().valid(0, 0.5, 1, 1.2, 1.5, 2, 2.5, 3).optional(),
  minimumHopper: Joi.number().integer().min(1).max(1000).optional(),
  maximumHopper: Joi.number().integer().min(1).max(5000).optional(),
  hopperRefillInterval: Joi.number().integer().min(5).max(3600).optional(),
  wrapUpTime: Joi.number().integer().min(0).max(3600).optional(),
  maximumAbandonRate: Joi.number().min(0).max(0.2).optional(),
  maximumSimultaneousCalls: Joi.number().integer().min(1).max(500).optional(),
  maximumCallsPerAgent: Joi.number().min(0.5).max(5).optional(),
  callTimeout: Joi.number().integer().min(5).max(600).optional(),
  ringTimeout: Joi.number().integer().min(5).max(300).optional(),
  agentReservationTime: Joi.number().integer().min(1).max(300).optional(),
  maximumQueueWait: Joi.number().integer().min(1).max(600).optional(),
  callPriority: Joi.string().max(40).optional(),
  localCallTime: Joi.boolean().optional(),
  emergencyStopped: Joi.boolean().optional(),
  maxRetries:  Joi.number().min(0).max(10).optional(),
  retryDelay:  Joi.number().min(30).max(86400).optional(),
  script:      Joi.string().max(5000).optional().allow(''),
  startTime:   Joi.string().pattern(/^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$/).optional(),
  endTime:     Joi.string().pattern(/^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$/).optional(),
  timezone:    Joi.string().optional(),
})
